services:
  server:
    container_name: knowledgebase
    build: ../KnowledgeBase
    ports:
      - 9010-9020:9010-9020
      - 8080:8080
    env_file:
      - ./.env.dev
    volumes:
      - ./:/root/Knowledgebase/
      - /home/alex/.conan2/:/root/.conan2/
    depends_on:
      - db
  db:
    container_name: postgres
    image: postgres
    environment:
      - "POSTGRES_USER=website"
      - "POSTGRES_PASSWORD=123"
      - "POSTGRES_DB=website_dev"
    ports:
      - "6432:5432"
